site_name: EverQuest Emulator
site_description: A long standing passionate EverQuest Emulator project started in 2001
site_url: 'https://github.com/EQEmu/Server/'
site_dir: /var/www/html/docs.akkadius.com/
repo_name: EQEmu/Server
repo_url: 'https://github.com/EQEmu/Server'
edit_uri: ''
theme:
  name: material
  feature:
    tabs: true
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai
  - admonition
  - toc:
      permalink: true
pages:
  - Server:
      - Server Install:
          - Windows: server/Windows-Server.md
          - Linux: server/Linux-Server.md
          - Dev Server Folders: server/Development-Server-Setup.md
      - Server Assets:
          - Asset Repositories: server/Server-Asset-Repositories.md
          - Updating Assets: server/Updating-Server-Assets.md
      - Configuration:
          - eqemu_config: server/eqemu_config.md
          - PvP: server/PvP.md
      - Logging System:
          - How to Use: server/logging-system.md
          - Categories: server/logging-categories.md
          - For Developers: server/logging-for-developers.md
          - Packet Logging: server/packet-logging.md
